## DATA PREPARATION

### Dataset used : https://archive.ics.uci.edu/dataset/319/mhealth+dataset

## About the Dataset

The MHEALTH (Mobile HEALTH) dataset comprises body motion and vital signs recordings for ten volunteers of diverse profile while performing several physical activities. Sensors placed on the subject's chest, right wrist, and left ankle are used to measure the motion experienced by diverse body parts, namely, acceleration, rate of turn, and magnetic field orientation. The sensor positioned on the chest also provides 2-lead ECG measurements, which can be potentially used for basic heart monitoring, checking for various arrhythmias, or looking at the effects of exercise on the ECG.

---

## Dataset Summary

**Activities:** 12
**Sensor devices:** 3
**Subjects:** 10

---

## Experimental Setup

The collected dataset comprises body motion and vital signs recordings for ten volunteers of diverse profile while performing 12 physical activities (Table 1). Shimmer2 [BUR10] wearable sensors were used for the recordings. The sensors were respectively placed on the subject's chest, right wrist, and left ankle and attached by using elastic straps.

The use of multiple sensors permits us to measure the motion experienced by diverse body parts, namely, the acceleration, the rate of turn, and the magnetic field orientation, thus better capturing the body dynamics.

The sensor positioned on the chest also provides 2-lead ECG measurements which are not used for the development of the recognition model but rather collected for future work purposes. This information can be used, for example, for basic heart monitoring, checking for various arrhythmias, or looking at the effects of exercise on the ECG.

All sensing modalities are recorded at a sampling rate of 50 Hz, which is considered sufficient for capturing human activity.

## Activity Set

The activity set is listed in the following:

| Activity Label | Activity Description | Repetitions/Duration |
|---|---|---|
| L1 | Standing still | 1 min |
| L2 | Sitting and relaxing | 1 min |
| L3 | Lying down | 1 min |
| L4 | Walking | 1 min |
| L5 | Climbing stairs | 1 min |
| L6 | Waist bends forward | 20x |
| L7 | Frontal elevation of arms | 20x |
| L8 | Knees bending (crouching) | 20x |
| L9 | Cycling | 1 min |
| L10 | Jogging | 1 min |
| L11 | Running | 1 min |
| L12 | Jump front & back | 20x |

**NOTE:** In brackets are the number of repetitions (Nx) or the duration of the exercises (min).

## MHEALTH Dataset Data Format

The MHEALTH dataset is organized into separate log files for each subject, named `mHealth_subject<SUBJECT_ID>.log`. These files contain sensor readings and activity labels, structured as follows:

### Columns:

| Column Number | Sensor & Measurement | Description |
|---|---|---|
| 1 | Chest Sensor | Acceleration (X-axis) |
| 2 | Chest Sensor | Acceleration (Y-axis) |
| 3 | Chest Sensor | Acceleration (Z-axis) |
| 4 | ECG | Signal (Lead 1) |
| 5 | ECG | Signal (Lead 2) |
| 6 | Left Ankle Sensor | Acceleration (X-axis) |
| 7 | Left Ankle Sensor | Acceleration (Y-axis) |
| 8 | Left Ankle Sensor | Acceleration (Z-axis) |
| 9 | Left Ankle Sensor | Gyroscope (X-axis) |
| 10 | Left Ankle Sensor | Gyroscope (Y-axis) |
| 11 | Left Ankle Sensor | Gyroscope (Z-axis) |
| 12 | Left Ankle Sensor | Magnetometer (X-axis) |
| 13 | Left Ankle Sensor | Magnetometer (Y-axis) |
| 14 | Left Ankle Sensor | Magnetometer (Z-axis) |
| 15 | Right Lower Arm Sensor | Acceleration (X-axis) |
| 16 | Right Lower Arm Sensor | Acceleration (Y-axis) |
| 17 | Right Lower Arm Sensor | Acceleration (Z-axis) |
| 18 | Right Lower Arm Sensor | Gyroscope (X-axis) |
| 19 | Right Lower Arm Sensor | Gyroscope (Y-axis) |
| 20 | Right Lower Arm Sensor | Gyroscope (Z-axis) |
| 21 | Right Lower Arm Sensor | Magnetometer (X-axis) |
| 22 | Right Lower Arm Sensor | Magnetometer (Y-axis) |
| 23 | Right Lower Arm Sensor | Magnetometer (Z-axis) |
| 24 | Activity Label | (0 = Null class, other numbers represent specific activities) |


### Rows:

Each row in the file represents a single sample of data collected from all sensors at a specific time point.


### Activity Labels:

Numeric labels are used to identify the activity being performed by the subject during that sample. For example, the label '4' corresponds to the 'Walking' activity. A full list of activities and their corresponding labels is provided in the dataset documentation.

Converting all log files into csv files

In [1]:
import pandas as pd

# Input and output file paths
input_file = 'logs_data/mHealth_subject10.log'  
output_file = 'logs_data/subject10_ecg_data.csv'

# Define column names as per documentation
columns = [
    "chest_acc_x", "chest_acc_y", "chest_acc_z",
    "ecg_1", "ecg_2",
    "la_acc_x", "la_acc_y", "la_acc_z",
    "la_gyro_x", "la_gyro_y", "la_gyro_z",
    "la_mag_x", "la_mag_y", "la_mag_z",
    "ra_acc_x", "ra_acc_y", "ra_acc_z",
    "ra_gyro_x", "ra_gyro_y", "ra_gyro_z",
    "ra_mag_x", "ra_mag_y", "ra_mag_z",
    "activity"
]

# Read the tab-separated log file
df = pd.read_csv(input_file, sep='\t', header=None, names=columns)

# Save to CSV
df.to_csv(output_file, index=False)

print(f"Converted: {output_file}")

Converted: logs_data/subject10_ecg_data.csv

In [2]:
import pandas as pd
import glob

# Pattern to match all subject CSVs
csv_files = glob.glob("logs_data/subject*_ecg_data.csv")

# List to hold each subject's data
df_list = []

for file in csv_files:
    df = pd.read_csv(file, header=None)
    df_list.append(df)

# Combine all into one DataFrame
full_df = pd.concat(df_list, ignore_index=True)

# Optional: assign column names if you haven't yet
full_df.columns = [
    "acc_chest_x", "acc_chest_y", "acc_chest_z",
    "ecg_1", "ecg_2",
    "acc_ankle_x", "acc_ankle_y", "acc_ankle_z",
    "gyro_ankle_x", "gyro_ankle_y", "gyro_ankle_z",
    "magnet_ankle_x", "magnet_ankle_y", "magnet_ankle_z",
    "acc_arm_x", "acc_arm_y", "acc_arm_z",
    "gyro_arm_x", "gyro_arm_y", "gyro_arm_z",
    "magnet_arm_x", "magnet_arm_y", "magnet_arm_z",
    "label"
]

C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)
C:\Users\MACHINE\AppData\Local\Temp\ipykernel_30208\904941148.py:11: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None)

In [3]:
full_df.to_csv("combined_mhealth_data.csv", index=False)

In [4]:
full_df.head()

,acc_chest_x,acc_chest_y,acc_chest_z,ecg_1,ecg_2,acc_ankle_x,acc_ankle_y,acc_ankle_z,gyro_ankle_x,gyro_ankle_y,...,acc_arm_x,acc_arm_y,acc_arm_z,gyro_arm_x,gyro_arm_y,gyro_arm_z,magnet_arm_x,magnet_arm_y,magnet_arm_z,label
0,chest_acc_x,chest_acc_y,chest_acc_z,ecg_1,ecg_2,la_acc_x,la_acc_y,la_acc_z,la_gyro_x,la_gyro_y,...,ra_acc_x,ra_acc_y,ra_acc_z,ra_gyro_x,ra_gyro_y,ra_gyro_z,ra_mag_x,ra_mag_y,ra_mag_z,activity
1,-9.6997,-0.87525,-0.96298,-0.029304,-0.07954,0.28409,-9.5692,1.4931,0.70501,-0.48968,...,-0.9863,-8.7188,4.1161,0.6451,-0.45175,0.69181,0.71991,0.17803,0.37363,0
2,-9.489,-0.80103,-1.1037,-0.062794,-0.092098,0.41798,-9.698,1.488,0.70501,-0.48968,...,-0.98795,-9.0372,4.2773,0.66667,-0.44353,0.6681,0.5404,0.17978,0.37002,0
3,-9.5541,-1.0831,-1.2448,-0.075353,-0.11722,0.33479,-9.5896,1.4405,0.69388,-0.48593,...,-0.89327,-8.7099,4.0124,0.66667,-0.44353,0.6681,0.72539,0.72599,0.72927,0
4,-9.368,-0.79141,-0.93438,-0.092098,-0.12977,0.27516,-9.648,1.5412,0.69388,-0.48593,...,-0.95632,-8.7986,4.1434,0.66667,-0.44353,0.6681,0.54392,0.53186,-0.71646,0

In [5]:
full_df.describe()

,acc_chest_x,acc_chest_y,acc_chest_z,ecg_1,ecg_2,acc_ankle_x,acc_ankle_y,acc_ankle_z,gyro_ankle_x,gyro_ankle_y,...,acc_arm_x,acc_arm_y,acc_arm_z,gyro_arm_x,gyro_arm_y,gyro_arm_z,magnet_arm_x,magnet_arm_y,magnet_arm_z,label
count,1215755.000,1.215755e+06,1.215755e+06,1.215755e+06,1.215755e+06,1215755.000,1215755.000,1215755.000,1.215755e+06,1.215755e+06,...,1215755.000,1215755.000,1215755.000,1.215755e+06,1.215755e+06,1.215755e+06,1215755,1215755,1215755,1215755
unique,216450.000,4.602990e+05,4.672620e+05,4.890000e+03,5.819000e+03,433522.000,166523.000,495416.000,3.112000e+03,3.414000e+03,...,371789.000,289985.000,280331.000,3.243000e+03,3.216000e+03,2.934000e+03,481431,471210,492359,22
top,-10.037,-1.132600e+00,-1.019700e+00,-1.214000e-01,-8.791200e-02,19.596,-19.338,-18.938,-3.525000e-01,-8.086300e-01,...,-20.654,-18.922,-18.227,-7.137300e-01,-9.650900e-01,8.987100e-01,0.36262,0.35578,-0.35732,0
freq,153.000,4.500000e+01,3.200000e+01,6.542000e+03,7.098000e+03,312.000,784.000,440.000,2.522000e+03,5.046000e+03,...,64.000,236.000,325.000,2.404000e+03,2.790000e+03,2.140000e+03,1892,1892,1892,639805

In [6]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215755 entries, 0 to 1215754
Data columns (total 24 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   acc_chest_x     1215755 non-null  object
 1   acc_chest_y     1215755 non-null  object
 2   acc_chest_z     1215755 non-null  object
 3   ecg_1           1215755 non-null  object
 4   ecg_2           1215755 non-null  object
 5   acc_ankle_x     1215755 non-null  object
 6   acc_ankle_y     1215755 non-null  object
 7   acc_ankle_z     1215755 non-null  object
 8   gyro_ankle_x    1215755 non-null  object
 9   gyro_ankle_y    1215755 non-null  object
 10  gyro_ankle_z    1215755 non-null  object
 11  magnet_ankle_x  1215755 non-null  object
 12  magnet_ankle_y  1215755 non-null  object
 13  magnet_ankle_z  1215755 non-null  object
 14  acc_arm_x       1215755 non-null  object
 15  acc_arm_y       1215755 non-null  object
 16  acc_arm_z       1215755 non-null  object
 17  gyro_arm_x      1215755 non-null  object
 18  gyro_arm_y      1215755 non-null  object
 19  gyro_arm_z      1215755 non-null  object
 20  magnet_arm_x    1215755 non-null  object
 21  magnet_arm_y    1215755 non-null  object
 22  magnet_arm_z    1215755 non-null  object
 23  label           1215755 non-null  object
dtypes: object(24)
memory usage: 222.6+ MB

Data conflicts

In [7]:
full_df['label'].unique()

array(['activity', '0', '5', '1', 1, 0, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12,
       '2', '3', '4', 5, '6', '7'], dtype=object)

In [8]:
# Remove any rows where the label column contains 'activity' or 'label'
full_df = full_df[full_df['label'] != 'label']
full_df = full_df[full_df['label'] != 'activity']

In [9]:
full_df['label'].unique()

array(['0', '5', '1', 1, 0, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, '2', '3',
       '4', 5, '6', '7'], dtype=object)

In [10]:
# Convert the 'label' column to integers (handles strings like '0', '4', etc.)
full_df['label'] = full_df['label'].astype(int)

In [11]:
full_df['label'].unique()

array([ 0,  5,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12])

In [12]:
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
activity_counts = full_df['label'].value_counts()
activity_counts

label
0     872550
5      30720
1      30720
2      30720
3      30720
4      30720
9      30720
10     30720
11     30720
7      29441
8      29337
6      28315
12     10342
Name: count, dtype: int64

Removing label 0 as it was a replacement for null values

In [14]:
full_df = full_df[full_df['label'] != 0]

In [15]:
activity_counts = full_df['label'].value_counts()
activity_counts

label
5     30720
1     30720
2     30720
3     30720
4     30720
9     30720
10    30720
11    30720
7     29441
8     29337
6     28315
12    10342
Name: count, dtype: int64

In [17]:
full_df.to_csv("combined_mhealth_data.csv", index=False)